# JPA
spring.jpa.show-sql=true

# SpringDoc
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Logging
logging.level.me.romangulevatiy.emerald=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
