# JPA
spring.jpa.show-sql=false

# SpringDoc
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Logging
logging.level.me.romangulevatiy.emerald=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.springframework.security=WARN

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
