spring.application.name=Emerald
spring.application.version=1.0
server.port=8080
server.servlet.context-path=/api

# Database
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-expiration=900000
jwt.refresh-expiration=604800000

# SpringDoc
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
